"""Add split column to audios

Revision ID: cb29e16d4e75
Revises: 64f5644519b3
Create Date: 2026-09-12 09:25:37.303489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb29e16d4e75'
down_revision: Union[str, Sequence[str], None] = '64f5644519b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modelos_id'), table_name='modelos')
    op.drop_table('modelos')
    op.add_column('audios', sa.Column('split', sa.String(length=20), nullable=False))
    op.alter_column('audios', 'confidence',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('audios', 'score_total',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audios', 'score_total',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('audios', 'confidence',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('audios', 'split')
    op.create_table('modelos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('estado', mysql.ENUM('ELIMINADO', 'DISPONIBLE', 'TRAINING'), nullable=False),
    sa.Column('referencia', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_modelos_id'), 'modelos', ['id'], unique=False)
    # ### end Alembic commands ###
